### ISSUE TITLE
v6 Roadmap

### ISSUE THREAD

**Issue by EDM115** [EDM115/unzip-bot#165]
## This issue is tightly linked to #38
- [ ] All features from it needs to be added
- [ ] All issues should be closed
- [ ] This update's release date must ideally be before `1st September 2023`
- [x] *optionnal* The best features could be shipped when we reach 10k users

### Important note !
The costs of the server are rising, and if I can keep it alive for the moment, I'm not sure if I can continue in the future...  
I will start to pay 100% of the costs on `1st December 2023`, so any help is appreciated 🥺  

### How to donate ?
+ [PayPal](https://www.paypal.me/8EDM115)
+ [BuyMeACoffee](https://www.buymeacoffee.com/edm115)
+ [Send crypto](https://edm115.shadd.eu.org/) (common wallet adresses here, [pm me](https://t.me/EDM115) for adresses of other specific wallets)
+ [GitHub Sponsors](https://github.com/sponsors/EDM115)
+ [Built-in Telegram](https://t.me/EDM115bots/170)
