### ISSUE TITLE
[ROADMAP] The future of unzip-bot (v7)

### ISSUE THREAD

**Issue by EDM115** [EDM115/unzip-bot#296]
Development have stayed pretty stale over the course of the past months, but I *might* have free time soon so I'm sorting everything out here (preparing updates for **v7**)  

#### Everything that needs to be done asap to start fresh from a solid base
- [ ] #356
- [ ] Refactor everything, separate functions (see #267)
- [ ] Optimize the recurrent tasks (see #285)
- [x] Redo the docker image size, try to use alpine if possible (see #249 & #286)
- [x] Change the way strings are used, would allow multiple languages (see #179)
- [ ] Simplify the commands list, make a unified settings page (see #173)
- [ ] Allow to cancel downloads (the button is here since 2 years but never worked) (see #28 & #245)
- [x] Switch frameworks and clean the packages used (see #258)
- [ ] Add the VIP plan system along a way better way to handle it admin-side (see #205)

#### Stuff that is less or more required to start the paid plan, in hope to monetize the bot so I can actually afford the servers (else the bot will purely die)
- [ ] Update the README to reflect the changes (see #240)
- [ ] Add a proper documentation of the code
- [ ] Expose a port and run an API to get some stats, useful for both monitoring the bot's health and get real-time insights for the [website](https://edm115.dev/unzip) (#452)
- [ ] Speaking of it, revamp the website. This will go along a much deeper transformation of my website so not for now (see https://github.com/EDM115/website/issues/51)
- [ ] Allow to browse the archives much better (not to the point where I implement a search, but still something better that a dumb list of 96 items) (see #169, #174 & #309)
- [ ] Extract splitted archives from multiple URL (#306)
- [x] Fix all paths escaping issues (see #295)
- [ ] Implement interfaces (#401)

#### These things are the cherry on top that will make the v7 a true masterpiece
- [ ] Save a list of passwords to try (see #144), as well as a list of thumbnails
- [ ] Enhance interface so users have a better glimpse at what happens (see #176 & #204)
- [ ] Allow to get a whitelist and *several* bot owners (see #288)
- [ ] Make a system that automatically bans people going against the bot's rules (see #289)
- [ ] Gradually add more perks to VIP users (multiple extracts, which would need a complete revamp of the current system, working in groups, more sources to download from, ability to retry tasks after a restart/wrong password, ability to compress files, ...)
- [ ] A telegram link that points to an archive should be processed
- [x] Get a way to support archives in .z×× or .r××
- [ ] Add a web support, with clean interface, mandatory login (account based, thanks to the new db, oauth may come later), size limit (probably 500Mb) but still password & URL support and a link to TG for more features 

---

> Unpinned #38 and #165 so we get a proper view of what's urgent. Also check them to see what's implemented and what's not  

> [!IMPORTANT]  
> The deadline I've set in the past is greatly crossed, now it's time for me to switch for the better !  
> You can check these messages where I explain a lot of things ([0](https://t.me/EDM115bots/641) - [1](https://t.me/EDM115bots/729) - [2](https://t.me/EDM115bots/733) - [3](https://t.me/EDM115bots/742) - [4](https://t.me/EDM115bots/747))  
> But as of now, I pay a lot for these new servers (for testing first and then for deploying the bot on it) so any amount of money is appreciated and would greatly help in speeding up these updates and finance the servers
>  
> ### How to donate ?
> - [PayPal](https://www.paypal.me/8EDM115)
> - [BuyMeACoffee](https://www.buymeacoffee.com/edm115)
> - [GitHub Sponsors](https://github.com/sponsors/EDM115)
> - [Built-in Telegram](https://t.me/EDM115bots/698)

**Comment by EDM115** [comment]
<div class="markdown-alert markdown-alert-note" dir="auto"><p class="markdown-alert-title" dir="auto"><svg class="octicon octicon-info mr-2" viewBox="0 0 16 16" version="1.1" width="16" height="16" aria-hidden="true"><path d="M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8Zm8-6.5a6.5 6.5 0 1 0 0 13 6.5 6.5 0 0 0 0-13ZM6.5 7.75A.75.75 0 0 1 7.25 7h1a.75.75 0 0 1 .75.75v2.75h.25a.75.75 0 0 1 0 1.5h-2a.75.75 0 0 1 0-1.5h.25v-2h-.25a.75.75 0 0 1-.75-.75ZM8 6a1 1 0 1 1 0-2 1 1 0 0 1 0 2Z"></path></svg>Note</p><p dir="auto">The naming scheme will change from what I've said in <a href="https://github.com/EDM115/unzip-bot/releases/tag/7.0.0a">https://github.com/EDM115/unzip-bot/releases/tag/7.0.0a</a><br>
Basically, all these alpha versions will stay in v7<br>
v8 will hold minor changes once most of the work will be done (especially the refacto one)<br>
v9 will be skipped so once <strong>v10</strong> gets releases (perhaps the last release), the impact will be bigger and people will realize that the project changed to its core</p>
</div>



<blockquote>                    <img src="https://opengraph.githubassets.com/709ab230b05adfb8f3826d01781c79b2b48a053b0af64952f2cc82e22b2e0c64/EDM115/unzip-bot/releases/tag/7.0.0a" width="48" align="right" />                          <div>          <strong>                          <a href="https://github.com/EDM115/unzip-bot/releases/tag/7.0.0a">Release Version 7.0.0a [alpha] · EDM115/unzip-bot</a>                      </strong>        </div>                    <div>ImportantNaming scheme moving forward
Pre-releases of v7 will be in alpha at first (7.0.0a, 7.0.1a, ...)
They will then move to beta (ready for test) : 7.0.0b, 7.0.1b, ...
Finally, a release candid...</div>                      </blockquote>
